version: '3.7'

services:
  api:
    build: ./src
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: users
    volumes:
      - mysql_data_login:/var/lib/mysql

volumes:
  mysql_data_login:
