spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/users
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

      hibernate:
        ddl-auto: create
        show-sql: true
